{
 "title": "monitor-demo",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "按持续时间区间统计请求数",
   "type": "stat",
   "description": "按持续时间区间统计请求数\nsum by(le) (increase(monitor_demo_order_request_duration_seconds_bucket[1h]))",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(monitor_demo_order_request_duration_seconds_bucket[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最近一小时的总请求数",
   "type": "stat",
   "description": "sum(increase(monitor_demo_order_requests_total[1h]))",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(monitor_demo_order_requests_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "当前订单总数",
   "type": "stat",
   "description": "sum(monitor_demo_order_status_count)",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_demo_order_status_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "随时间变化的持续时间分布",
   "type": "heatmap",
   "description": "sum(rate(monitor_demo_order_request_duration_seconds_bucket[5m])) by (le)",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(monitor_demo_order_request_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "10分钟内的错误分布",
   "type": "piechart",
   "description": "# 按类型统计10分钟内的错误分布\nsum by(error_type) (increase(monitor_demo_order_requests_total{status=\"error\"}[10h]))",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(error_type) (increase(monitor_demo_order_requests_total{status=\"error\"}[10h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "订单各状态最近一小时的最大值",
   "type": "stat",
   "description": "max_over_time(monitor_demo_order_status_count[1h])",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(monitor_demo_order_status_count[1h])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": " 查询订单金额的中位数",
   "type": "timeseries",
   "description": "monitor_demo_order_amount_distribution{quantile=\"0.5\"}",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "monitor_demo_order_amount_distribution{quantile=\"0.5\"}",
     "legendFormat": "{{type}}-订单金额中位数"
    },
    {
     "expr": "monitor_demo_order_amount_distribution{quantile=\"0.9\"}",
     "legendFormat": "{{type}}-高价值订单（90%分位）"
    }
   ]
  },
  {
   "title": "最近5分钟的订单金额总和",
   "type": "timeseries",
   "description": "rate(monitor_demo_order_amount_distribution_sum[5m])",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "rate(monitor_demo_order_amount_distribution_sum[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "各状态订单分布",
   "type": "stat",
   "description": "monitor_demo_order_status_count",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_demo_order_status_count",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "timeseries",
   "description": "rate(monitor_demo_order_request_duration_seconds_sum[5m])\n  /\nrate(monitor_demo_order_request_duration_seconds_count[5m])",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(monitor_demo_order_request_duration_seconds_sum[5m])\n  /\nrate(monitor_demo_order_request_duration_seconds_count[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "95分位响应时间",
   "type": "timeseries",
   "description": "histogram_quantile(0.95, sum(rate(monitor_demo_order_request_duration_seconds_bucket[5m])) by (le))",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(monitor_demo_order_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95分位"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(monitor_demo_order_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "90分位"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(monitor_demo_order_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50分为"
    }
   ]
  },
  {
   "title": "查询订单处理时间的90%分位数",
   "type": "timeseries",
   "description": "查询订单处理时间的90%分位数\nmonitor_demo_order_processing_seconds{quantile=\"0.9\"}",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "monitor_demo_order_processing_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{method}}-0.9"
    },
    {
     "expr": "monitor_demo_order_processing_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{method}}-0.99"
    },
    {
     "expr": "monitor_demo_order_processing_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{method}}-0.5"
    }
   ]
  },
  {
   "title": "订单各个状态值",
   "type": "timeseries",
   "description": "monitor_demo_order_status_count",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "monitor_demo_order_status_count",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "订单按状态统计平均值",
   "type": "timeseries",
   "description": "avg by(status) (monitor_demo_order_status_count)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "avg by(status) (monitor_demo_order_status_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "按方法统计的请求率（仪表板查询）",
   "type": "timeseries",
   "description": "# 按方法统计的请求率（仪表板查询）\nsum by(method) (rate(monitor_demo_order_requests_total[5m]))",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(method) (rate(monitor_demo_order_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5分钟内的错误率",
   "type": "timeseries",
   "description": "sum(rate(monitor_demo_order_requests_total{status=\"error\"}[5m])) \n  / \nsum(rate(monitor_demo_order_requests_total[5m])) * 100",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum(rate(monitor_demo_order_requests_total{status=\"error\"}[5m])) \n  / \nsum(rate(monitor_demo_order_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}